### ISSUE TITLE
Controller wont  work 

### ISSUE THREAD

**Issue by chaaar36** [emoisback/Helldivers-2-Internal-Hack-Dll-Proxy-PoC#22]
controller stops working after dll placement on game folder. using big picture or steam input also wont work

**Comment by DeathWrench** [comment]
![image](https://github.com/emoisback/Helldivers-2-Internal-Hack-Dll-Proxy-PoC/assets/45341450/934a8697-f840-4b8d-987e-dbd4baea2f93)
![image](https://github.com/emoisback/Helldivers-2-Internal-Hack-Dll-Proxy-PoC/assets/45341450/31286f66-5a2f-4f40-9d85-4434bfdd356d)
Tried real quick since I don't play with a controller. It's working fine for me, I'm not in big picture mode tho.

**Comment by emoisback** [comment]
i dont have controller, so if its done ill close this.
